export const WIDGET_CREATING = 'WIDGET_CREATING'
export const WIDGET_CREATE_SUCCESS = 'WIDGET_CREATE_SUCCESS'
export const WIDGET_CREATE_ERROR = 'WIDGET_CREATE_ERROR'

export const WIDGET_REQUESTING = 'WIDGET_REQUESTING'
export const WIDGET_REQUEST_SUCCESS = 'WIDGET_REQUEST_SUCCESS'
export const WIDGET_REQUEST_ERROR = 'WIDGET_REQUEST_ERROR'
